# Generated by Django 5.0.6 on 2024-05-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0002_alter_ride_id_alter_vehicle_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("employee_id", models.CharField(max_length=255, unique=True)),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("mobile_number", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="ride",
            name="available_seats",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="make",
        ),
        migrations.AddField(
            model_name="ride",
            name="destination_latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ride",
            name="destination_longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ride",
            name="origin_latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ride",
            name="origin_longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ride",
            name="vehicle_type",
            field=models.CharField(default="car", max_length=255),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[("CR", "Car"), ("MC", "Motorcycle")],
                default="CR",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="arrival_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="departure_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ride",
            name="destination",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="ride",
            name="origin",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.RemoveField(
            model_name="ride",
            name="passengers",
        ),
        migrations.AlterField(
            model_name="ride",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rides.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="number_of_seats",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rides.employee",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rides.employee"
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="passengers",
            field=models.IntegerField(default=1),
        ),
    ]
