# Generated by Django 5.0.6 on 2024-05-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0003_employee_remove_ride_available_seats_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="arrival_time",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="owner",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="employees",
            field=models.ManyToManyField(to="rides.employee"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="ride",
            name="vehicle",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="ride",
            name="vehicle_type",
            field=models.CharField(default="CR", max_length=255),
        ),
    ]
