# Generated by Django 5.0.6 on 2024-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0004_remove_ride_arrival_time_remove_vehicle_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="arrival_time",
            field=models.DateTimeField(null=True),
        ),
    ]
