# Generated by Django 5.0.6 on 2024-05-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_riderequest_rideresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='riderequest',
            unique_together={('ride', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='rideresponse',
            unique_together={('ride_request', 'driver')},
        ),
    ]
