# Generated by Django 5.0.6 on 2024-05-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0007_alter_riderequest_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("A", "Accepted"),
                    ("R", "Rejected"),
                    ("C", "Cancelled"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="rideresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("A", "Accepted"),
                    ("R", "Rejected"),
                    ("C", "Cancelled"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
