# Generated by Django 5.0.6 on 2024-05-31 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0008_alter_riderequest_status_alter_rideresponse_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="riderequest",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="rideresponse",
            unique_together=set(),
        ),
    ]
